server:
  port: 9999

spring:
  application:
    name: spring-data-redis

  output:
    ansi:
      enabled: always

  redis:
    host: localhost
    port: 6379
    password: admin123!
  profiles:
    active: local

logging:
  level:
    com.roopy: DEBUG